openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
tags:
  - name: quotes-end-point
    description: Gestion des quotes
paths:
  /quotes:
    get:
      tags:
        - quotes-end-point
      description: Liste toutes les quotes
      operationId: listQuotesUsingGET
      parameters:
        - in: query
          name: author
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - quotes-end-point
      summary: addQuote
      operationId: addQuoteUsingPOST
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Quote'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /quotes/{id}:
    get:
      tags:
        - quotes-end-point
      summary: ListQuote
      operationId: ListQuoteUsingGET
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Quote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Quote:
      type: object
      properties:
        author:
          type: string
        citation:
          type: string
        id:
          type: integer
          format: int32
      title: Quote
