swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
host: 'localhost:9090'
basePath: /api
schemes:
- http
tags:
  - name: quotes-end-point
    description: Gestion des quotes
paths:
  /quotes:
    get:
      tags:
        - quotes-end-point
      summary: Liste toutes les quotes
      operationId: listQuotesUsingGET
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Quote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - quotes-end-point
      summary: addQuote
      operationId: addQuoteUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: quote
          description: quote
          required: true
          schema:
            $ref: '#/definitions/Quote'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/quotes/{id}':
    get:
      tags:
        - quotes-end-point
      summary: ListQuote
      operationId: ListQuoteUsingGET
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Quote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Quote:
    type: object
    properties:
      author:
        type: string
      citation:
        type: string
      id:
        type: integer
        format: int32
    title: Quote
